name: Keybomb
version: ${project.version}
main: com.dhaboi.keybomb.main
api-version: 1.16
authors: [dhaboi]
description: a custom made keybomb plugin made for a server
website: dhanotboi.github.io
commands:
  bomb:
    description: This command is used for the bomb plugin, do /bomb help to learn more
    aliases: b
    usage: /<command> <arg1> <arg2> <arg3> <arg4>
    permission: bomb.dev
    permission-message: Get Better
  rarekey:
    description: gives a player a rare key
    aliases: rk
    usage: /rarekey <player>
    permission: bomb.dev
    permission-message: Get Better
  mythicalkey:
    description: gives a player a mythical key
    aliases: mk
    usage: /mythicalkey <player>
    permission: bomb.dev
    permission-message: Get Better
  tavernkey:
    description: gives a player a tavern key
    aliases: tk
    usage: /tavernkey <player>
    permission: bomb.dev
    permission-message: Get Better
permissions:
  bomb.dev:
    description: allows you to use all of the commands in the bomb plugin.

